project_name: contributoor-installer

before:
  hooks:
    - go mod tidy

builds:
  - id: contributoor-installer
    main: ./cmd/cli
    binary: contributoor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ethpandaops/contributoor-installer/internal/installer.Release={{.Tag}} -X github.com/ethpandaops/contributoor-installer/internal/installer.GitCommit={{.ShortCommit}} -X github.com/ethpandaops/contributoor-installer/internal/installer.GOOS={{.Os}} -X github.com/ethpandaops/contributoor-installer/internal/installer.GOARCH={{.Arch}}
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - format: tar.gz
    wrap_in_directory: false
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README*
      - LICENSE*
      - install.sh
      - docker-compose.yml
      - docker-compose.metrics.yml
      - docker-compose.health.yml
      - docker-compose.network.yml

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'