before:
  hooks:
    - go mod tidy

builds:
  - id: contributoor-installer
    main: ./cmd/cli
    binary: contributoor
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    wrap_in_directory: false
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README*
      - LICENSE*
      - install.sh
      - docker-compose.yml

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'