services:
  sentry:
    container_name: contributoor
    image: ethpandaops/contributoor:${CONTRIBUTOOR_VERSION}-${CONTRIBUTOOR_ARCH_SUFFIX}
    entrypoint: ["/usr/local/bin/sentry"]
    command: ["--config=/config/config.yaml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${CONTRIBUTOOR_CONFIG_PATH}/config.yaml:/config/config.yaml:ro
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
