services:
  sentry:
    image: ethpandaops/contributoor:${CONTRIBUTOOR_VERSION}
    entrypoint: ["/usr/local/bin/sentry"]
    command: ["--config=/config/config.yaml"]
    networks:
      - contributoor
    ports:
      - "${CONTRIBUTOOR_METRICS_ADDRESS}:${CONTRIBUTOOR_METRICS_PORT}:${CONTRIBUTOOR_METRICS_PORT}"
    extra_hosts:
      - "127.0.0.1:host-gateway"
      - "localhost:host-gateway"
    volumes:
      - type: bind
        source: "${CONTRIBUTOOR_CONFIG_PATH}/config.yaml"
        target: "/config/config.yaml"
        read_only: true
    restart: always

networks:
  contributoor:
    driver: bridge
