// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethpandaops/contributoor-installer/internal/sidecar (interfaces: DockerSidecar)
//
// Generated by this command:
//
//	mockgen -package mock -destination mock/docker.mock.go github.com/ethpandaops/contributoor-installer/internal/sidecar DockerSidecar
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDockerSidecar is a mock of DockerSidecar interface.
type MockDockerSidecar struct {
	ctrl     *gomock.Controller
	recorder *MockDockerSidecarMockRecorder
}

// MockDockerSidecarMockRecorder is the mock recorder for MockDockerSidecar.
type MockDockerSidecarMockRecorder struct {
	mock *MockDockerSidecar
}

// NewMockDockerSidecar creates a new mock instance.
func NewMockDockerSidecar(ctrl *gomock.Controller) *MockDockerSidecar {
	mock := &MockDockerSidecar{ctrl: ctrl}
	mock.recorder = &MockDockerSidecarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDockerSidecar) EXPECT() *MockDockerSidecarMockRecorder {
	return m.recorder
}

// IsRunning mocks base method.
func (m *MockDockerSidecar) IsRunning() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockDockerSidecarMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockDockerSidecar)(nil).IsRunning))
}

// Start mocks base method.
func (m *MockDockerSidecar) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockDockerSidecarMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockDockerSidecar)(nil).Start))
}

// Stop mocks base method.
func (m *MockDockerSidecar) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockDockerSidecarMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDockerSidecar)(nil).Stop))
}

// Update mocks base method.
func (m *MockDockerSidecar) Update() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update")
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockDockerSidecarMockRecorder) Update() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDockerSidecar)(nil).Update))
}
