name: check-typos

on:
  pull_request:
    branches:
      - master

jobs:
  check-typos:
    name: Check typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.29.9