name: go-test

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  checks: write

jobs:
  go-tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go
        uses: ./.github/workflows/go-setup

      - name: Run Tests
        run: go test -v -race -json ./... > test.json

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: test-results
          path: test.json

  annotate:
    needs: go-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download test results
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: test-results